// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBezBOg4XqEB5VpPLeBjfaSbwzgFCNZbPw',
    appId: '1:774566526060:web:a304730090aeeb23f52c49',
    messagingSenderId: '774566526060',
    projectId: 'practiceappmy',
    authDomain: 'practiceappmy.firebaseapp.com',
    databaseURL: 'https://practiceappmy-default-rtdb.firebaseio.com',
    storageBucket: 'practiceappmy.appspot.com',
    measurementId: 'G-2RK4FKR1SD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzA-vCpSKnEG8jc3KYI5_vSZQIU4MYMZ4',
    appId: '1:774566526060:android:c51bbb277a69f15ff52c49',
    messagingSenderId: '774566526060',
    projectId: 'practiceappmy',
    databaseURL: 'https://practiceappmy-default-rtdb.firebaseio.com',
    storageBucket: 'practiceappmy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBom8SdlKFjDrNjdjIpfTjr0YdnPra8XBo',
    appId: '1:774566526060:ios:afed298a5e66111af52c49',
    messagingSenderId: '774566526060',
    projectId: 'practiceappmy',
    databaseURL: 'https://practiceappmy-default-rtdb.firebaseio.com',
    storageBucket: 'practiceappmy.appspot.com',
    androidClientId: '774566526060-0se17ee5g8t5bosatobdiaktqq1s1kq6.apps.googleusercontent.com',
    iosClientId: '774566526060-bg8miernbsn2297jmcf24bh3sdf8ncgf.apps.googleusercontent.com',
    iosBundleId: 'com.konect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBezBOg4XqEB5VpPLeBjfaSbwzgFCNZbPw',
    appId: '1:774566526060:web:5f70d522610b26d7f52c49',
    messagingSenderId: '774566526060',
    projectId: 'practiceappmy',
    authDomain: 'practiceappmy.firebaseapp.com',
    databaseURL: 'https://practiceappmy-default-rtdb.firebaseio.com',
    storageBucket: 'practiceappmy.appspot.com',
    measurementId: 'G-6HBMC3BM2N',
  );
}
